### ISSUE TITLE
does not work - gives estimations of 0

### ISSUE THREAD

**Issue by 7flash** [okibcn/wslcompact#3]
![image](https://user-images.githubusercontent.com/4569866/217572184-39a6c2ce-d2ec-4768-a5a6-52a40466bcc7.png)

**Comment by okibcn** [comment]
@7flash, do you have any special user configuration within your Ubuntu-22.04? the Estimated size is provided by wsl, so it might be a configuration colliding with it.

Please try these two commands from PowerShell:
```pwsh
wsl --system -d Ubuntu-22.04 -e df /mnt/wslg/distro
```
```pwsh
wsl -d Ubuntu-22.04 -e df /
```
And this one from within a WSL shell session inside Ubuntu-22.04:
```bash
\df /
```

They should return the same text, but for some reason, in your case, it is behaving differently. It would be nice if you copy-n-paste the output of these three tests. Better than a screenshot.

**Comment by okibcn** [comment]
[wslcompact v7.0](https://github.com/okibcn/wslcompact/releases/tag/7.0) brings an update to the size estimation. It probably solved your issue. Follow the [update instructions](https://github.com/okibcn/wslcompact#installation) to properly update your **wslcompact**.

If it continues failing we can reopen the issue.
